import type { Metadata } from "next";
import "./globals.css";
import LayoutWrapper from "./components/LayoutWrapper";
import { Toaster } from "sonner"; // 🆕 اضافه شد

export const metadata: Metadata = {
  title: "فراپارت",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  headerOnly,
}: {
  children: React.ReactNode;
  headerOnly: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl">
      <body suppressHydrationWarning>
        {/* صفحات عادی */}
        <LayoutWrapper>{children}</LayoutWrapper>

        <Toaster
          position="top-center"
          richColors
          closeButton
          dir="rtl"
          toastOptions={{
            style: {
              fontFamily: "yekanRegular, sans-serif",
            },
          }}
        />
      </body>
    </html>
  );
}
