import type { Metadata } from "next";
import "./globals.css";
import LayoutWrapper from "./components/LayoutWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  headerOnly,
}: {
  children: React.ReactNode;
  headerOnly: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl">
      <body suppressHydrationWarning>
        {/* صفحات عادی */}
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
